version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: smart_tech_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${SMART_TECH_PASSWORD_DOCKER_COMPOSE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smart_tech_shop"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - smart_tech_postgres_data:/var/lib/postgresql/data
    networks:
      - smart_tech_network

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: smart_tech_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smarttech.com
      PGADMIN_DEFAULT_PASSWORD: ${SMART_TECH_DOCKER_COMPOSE}
    ports:
      - "8080:80"
    volumes:
      - smart_tech_pgadmin_data:/var/lib/pgadmin
    networks:
      - smart_tech_network
    depends_on:
      - postgres

volumes:
  smart_tech_postgres_data:
  smart_tech_pgadmin_data:

networks:
  smart_tech_network:
    name: smart_tech_network
